enum ImageDataFetchState {
  IS_IMAGE_DATA_LOADING,
  IS_IMAGE_DATA_LOADED,
  ERROR_ENCOUNTERED_WHILE_FETCHING_IMAGE_DATA,
  NO_IMAGE_DATA
}

enum VideoDataFetchState {
  IS_VIDEO_DATA_LOADING,
  IS_VIDEO_DATA_LOADED,
  ERROR_ENCOUNTERED_WHILE_FETCHING_VIDEO_DATA,
  NO_VIDEO_DATA
}

enum ConnectivityStatus { Wifi, Mobile, Offline }

enum ThemeModes { DARK_THEME, LIGHT_THEME, SYSTEM_THEME }
